version: 2

workflows:
  version: 2
  build:
    jobs:
      - build_lowest
      - build_highest

defaults: &defaults
  docker:
    - image: previousnext/php-apache:7.3-3.x-dev
  working_directory: /data
  steps:
    - checkout
    - run: composer update --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader ${PREFER_LOWEST}
    - run: ./bin/phpcs --colors --report=full
    - run: mkdir -p build/phpunit
    - run: ./bin/phpunit --log-junit build/phpunit/results.xml
    - store_test_results:
        path: build

jobs:
  build_lowest:
    <<: *defaults
    docker:
      - image: previousnext/php-apache:7.1-3.x-dev
    environment:
      - PREFER_LOWEST: --prefer-lowest
  build_highest:
    <<: *defaults
    environment:
      - PREFER_LOWEST: ''

